import { MigrationInterface, QueryRunner } from "typeorm";

export class AddCategoryImageTable1775041340347 implements MigrationInterface {
    name = 'AddCategoryImageTable1775041340347'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_PROFILES_EMAIL"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PROFILES_MOBILE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PROFILES_COUNTRY_SHORTCODE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PROFILES_COUNTRY_MOBILE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PRODUCTS_SUPPLIER_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USERS_USER_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USERS_EMAIL_VERIFIED"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USERS_TYPE_CREATED"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USERS_VERIFIED_CREATED"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USERS_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ORDERS_USER_CREATED"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ORDERS_STATUS_CREATED"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_NOTIFICATIONS_USER_CREATED"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_NOTIFICATIONS_USER_READ"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_NOTIFICATIONS_USER_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_NOTIFICATIONS_STATUS_CREATED"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_NOTIFICATIONS_ISREAD_CREATED"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_NOTIFICATIONS_USERID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_NOTIFICATIONS_ISREAD"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_NOTIFICATIONS_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CART_ITEMS_USER_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CART_ITEMS_PRODUCT_ID"`);
        await queryRunner.query(`CREATE TABLE "category_images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "url" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "category_id" uuid, CONSTRAINT "PK_fd32228261460eca2567579ec42" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "image"`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068"`);
        await queryRunner.query(`ALTER TABLE "product_images" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_images" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_images" ALTER COLUMN "product_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_0ec433c1e1d444962d592d86c86"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "supplier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "category_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "name" character varying NOT NULL DEFAULT 'Velora'`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "tagline"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "tagline" character varying NOT NULL DEFAULT 'Premium E-Commerce Solutions'`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "address" character varying NOT NULL DEFAULT '123 Business Avenue, New York, NY 10001'`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "email" character varying NOT NULL DEFAULT 'contact@velora.com'`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "phone" character varying NOT NULL DEFAULT '+1 (555) 123-4567'`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "website"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "website" character varying NOT NULL DEFAULT 'https://velora.com'`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "logoUrl"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "logoUrl" character varying NOT NULL DEFAULT 'https://res.cloudinary.com/dcegoonge/image/upload/v1774418520/company-logo/hugpvjg6op8enixjsrhk.png'`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_a922b820eeef29ac1c6800e826a"`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "path"`);
        await queryRunner.query(`ALTER TABLE "media" ADD "path" character varying`);
        await queryRunner.query(`ALTER TABLE "media" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "media" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_b7213c20c1ecdc6597abc8f1212"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_30e89257a105eab7648a35c7fce"`);
        await queryRunner.query(`ALTER TABLE "cart_items" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cart_items" ALTER COLUMN "product_id" SET NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_1682e055e2d130467c07c2f4eb" ON "profiles" ("country_shortcode", "mobile") `);
        await queryRunner.query(`CREATE INDEX "IDX_30b837eda8f1a71edd402eec72" ON "profiles" ("country_shortcode") `);
        await queryRunner.query(`CREATE INDEX "IDX_df6cb7dd5e02c7f6606ffb31c2" ON "profiles" ("mobile") `);
        await queryRunner.query(`CREATE INDEX "IDX_5b49bd22c967ce2829ca8f1772" ON "profiles" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ec433c1e1d444962d592d86c8" ON "products" ("supplier_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c9b5b525a96ddc2c5647d7f7fa" ON "users" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_f89f01eb6beb749b9771e76b9f" ON "users" ("is_email_verified", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_e7afc1c0fb322dd68effcb519b" ON "users" ("user_type", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_1abbfecef5aefa239aca51ccc5" ON "users" ("is_email_verified") `);
        await queryRunner.query(`CREATE INDEX "IDX_c6778957fcf0cd97c7e27f080e" ON "users" ("user_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_d39dd89d89fe12aa86872b7865" ON "orders" ("status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_fbfc1475fc6797244d160068cb" ON "orders" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_1846a75fabf533d10bf09142af" ON "notifications" ("isRead", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_9cc1d6981330422a3684f9b00f" ON "notifications" ("status", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef19dfa50221762de8ce35b043" ON "notifications" ("userId", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_5340fc241f57310d243e5ab20b" ON "notifications" ("userId", "isRead") `);
        await queryRunner.query(`CREATE INDEX "IDX_21e65af2f4f242d4c85a92aff4" ON "notifications" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_30e89257a105eab7648a35c7fc" ON "cart_items" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b7213c20c1ecdc6597abc8f121" ON "cart_items" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "category_images" ADD CONSTRAINT "FK_59ed1b18d3a243accc6d0003ac4" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_0ec433c1e1d444962d592d86c86" FOREIGN KEY ("supplier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_a922b820eeef29ac1c6800e826a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_b7213c20c1ecdc6597abc8f1212" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_30e89257a105eab7648a35c7fce" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_30e89257a105eab7648a35c7fce"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_b7213c20c1ecdc6597abc8f1212"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_a922b820eeef29ac1c6800e826a"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_0ec433c1e1d444962d592d86c86"`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068"`);
        await queryRunner.query(`ALTER TABLE "category_images" DROP CONSTRAINT "FK_59ed1b18d3a243accc6d0003ac4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b7213c20c1ecdc6597abc8f121"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30e89257a105eab7648a35c7fc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21e65af2f4f242d4c85a92aff4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5340fc241f57310d243e5ab20b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef19dfa50221762de8ce35b043"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9cc1d6981330422a3684f9b00f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1846a75fabf533d10bf09142af"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fbfc1475fc6797244d160068cb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d39dd89d89fe12aa86872b7865"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c6778957fcf0cd97c7e27f080e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1abbfecef5aefa239aca51ccc5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7afc1c0fb322dd68effcb519b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f89f01eb6beb749b9771e76b9f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9b5b525a96ddc2c5647d7f7fa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ec433c1e1d444962d592d86c8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b49bd22c967ce2829ca8f1772"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df6cb7dd5e02c7f6606ffb31c2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30b837eda8f1a71edd402eec72"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1682e055e2d130467c07c2f4eb"`);
        await queryRunner.query(`ALTER TABLE "cart_items" ALTER COLUMN "product_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cart_items" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_30e89257a105eab7648a35c7fce" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_b7213c20c1ecdc6597abc8f1212" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "media" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "path"`);
        await queryRunner.query(`ALTER TABLE "media" ADD "path" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_a922b820eeef29ac1c6800e826a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "logoUrl"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "logoUrl" character varying(500) NOT NULL DEFAULT 'https://res.cloudinary.com/dcegoonge/image/upload/v1774418520/company-logo/hugpvjg6op8enixjsrhk.png'`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "website"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "website" character varying(255) NOT NULL DEFAULT 'https://velora.com'`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "phone" character varying(50) NOT NULL DEFAULT '+1 (555) 123-4567'`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "email" character varying(255) NOT NULL DEFAULT 'contact@velora.com'`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "address" character varying(500) NOT NULL DEFAULT '123 Business Avenue, New York, NY 10001'`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "tagline"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "tagline" character varying(255) NOT NULL DEFAULT 'Premium E-Commerce Solutions'`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "name" character varying(255) NOT NULL DEFAULT 'Velora'`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "category_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "supplier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_0ec433c1e1d444962d592d86c86" FOREIGN KEY ("supplier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_images" ALTER COLUMN "product_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_images" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_images" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "image" character varying`);
        await queryRunner.query(`DROP TABLE "category_images"`);
        await queryRunner.query(`CREATE INDEX "IDX_CART_ITEMS_PRODUCT_ID" ON "cart_items" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_CART_ITEMS_USER_ID" ON "cart_items" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_NOTIFICATIONS_TYPE" ON "notifications" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_NOTIFICATIONS_ISREAD" ON "notifications" ("isRead") `);
        await queryRunner.query(`CREATE INDEX "IDX_NOTIFICATIONS_USERID" ON "notifications" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_NOTIFICATIONS_ISREAD_CREATED" ON "notifications" ("createdAt", "isRead") `);
        await queryRunner.query(`CREATE INDEX "IDX_NOTIFICATIONS_STATUS_CREATED" ON "notifications" ("createdAt", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_NOTIFICATIONS_USER_TYPE" ON "notifications" ("type", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_NOTIFICATIONS_USER_READ" ON "notifications" ("isRead", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_NOTIFICATIONS_USER_CREATED" ON "notifications" ("createdAt", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ORDERS_STATUS_CREATED" ON "orders" ("created_at", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ORDERS_USER_CREATED" ON "orders" ("created_at", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_USERS_CREATED_AT" ON "users" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_USERS_VERIFIED_CREATED" ON "users" ("created_at", "is_email_verified") `);
        await queryRunner.query(`CREATE INDEX "IDX_USERS_TYPE_CREATED" ON "users" ("created_at", "user_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_USERS_EMAIL_VERIFIED" ON "users" ("is_email_verified") `);
        await queryRunner.query(`CREATE INDEX "IDX_USERS_USER_TYPE" ON "users" ("user_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_PRODUCTS_SUPPLIER_ID" ON "products" ("supplier_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_PROFILES_COUNTRY_MOBILE" ON "profiles" ("country_shortcode", "mobile") `);
        await queryRunner.query(`CREATE INDEX "IDX_PROFILES_COUNTRY_SHORTCODE" ON "profiles" ("country_shortcode") `);
        await queryRunner.query(`CREATE INDEX "IDX_PROFILES_MOBILE" ON "profiles" ("mobile") `);
        await queryRunner.query(`CREATE INDEX "IDX_PROFILES_EMAIL" ON "profiles" ("email") `);
    }

}
